# @api = http://localhost:8000
@api = https://fazt-deno-tutorial.deno.dev

### get root
GET {{api}}

### tasks routes
GET {{api}}/tasks

### create tasks routes
POST {{api}}/tasks
Content-Type: application/json1

{
  "title": "Task 1",
  "description": "Task 1 description",
  "status": "todo"
}